# Generated by Django 5.0.14 on 2026-03-09 14:36

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_alter_company_id_alter_contact_id_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=500)),
                ('body', wagtail.fields.StreamField([('feature_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.TextBlock()), ('icon', wagtail.blocks.CharBlock())])), ('testimonial', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('author', wagtail.blocks.CharBlock()), ('company', wagtail.blocks.CharBlock())])), ('cta_section', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('button_text', wagtail.blocks.CharBlock()), ('button_url', wagtail.blocks.URLBlock())]))])),
                ('form_enabled', models.BooleanField(default=False)),
                ('form_title', models.CharField(blank=True, max_length=100)),
                ('form_fields', wagtail.fields.StreamField([('text_field', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('required', wagtail.blocks.BooleanBlock(required=False)), ('map_to_contact_field', wagtail.blocks.CharBlock())]))], blank=True)),
                ('success_url', models.URLField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('dynamic_rules', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='mailing_lists', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('preheader', models.CharField(blank=True, max_length=150)),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())])), ('product_recommendation', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()))])),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opens', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('unsubscribes', models.IntegerField(default=0)),
                ('target_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.mailinglist')),
            ],
        ),
    ]
