# Generated by Django 5.0.14 on 2026-03-09 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('field_changed', 'Specific Field Changed'), ('date_reached', 'Date Field Reached'), ('incoming_email', 'Incoming Email'), ('form_submitted', 'Form Submitted')], max_length=50)),
                ('trigger_config', models.JSONField()),
                ('conditions', models.JSONField(default=list)),
                ('actions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
